# Bounds
MIN_GENERATIONS: int = 1
MAX_GENERATIONS: int = 10_000

MIN_UPDATES_PER_S: int = 1
MAX_UPDATES_PER_S: int = 1_000_000

MIN_DIMENSION: int = 1
MAX_DIMENSION: int = 256

# Defaults
DEFAULT_NUM_OF_GENERATIONS: int = 32
DEFAULT_UPDATES_PER_S: int = 8
DEFAULT_DIMENSION_X: int = 16
DEFAULT_DIMENSION_Y: int = 16
DEFAULT_IS_GHOST_MODE: bool = True
