# Bounds
MIN_GENERATIONS: int = 1

MIN_DIMENSION: int = 1
MAX_DIMENSION: int = 256

# Defaults
DEFAULT_GENERATIONS: int = 32
DEFAULT_SPEED_S: float = 0.1

DEFAULT_WIDTH: int = 16
DEFAULT_HEIGHT: int = 16
